language: cpp
dist: xenial
os: linux
matrix:
  include:

    - compiler: clang
      addons:
        apt:
          sources:


          packages:
            - clang
      env:
        - COMPILER="CC=clang && CXX=clang++" BOOST_MAJOR_VERSION=1 BOOST_MINOR_VERSION=67 BOOST_RELEASE_VERSION=0


    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

      env:
           COMPILER="CC=gcc-7 && CXX=g++-7" BOOST_MAJOR_VERSION=1 BOOST_MINOR_VERSION=67 BOOST_RELEASE_VERSION=0


    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

      env:
           COMPILER="CC=gcc-6 && CXX=g++-6" BOOST_MAJOR_VERSION=1 BOOST_MINOR_VERSION=67 BOOST_RELEASE_VERSION=0


    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

      env:
           COMPILER="CC=gcc-5 && CXX=g++-5" BOOST_MAJOR_VERSION=1 BOOST_MINOR_VERSION=67 BOOST_RELEASE_VERSION=0




before_install:
  - eval ${COMPILER}
  # cmake
  - travis_retry sudo add-apt-repository -y ppa:andrew-fuller/cmake
install:
  # https://stackoverflow.com/a/32127147 on how to set the compiler!
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR}
  - INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/prefix
  - mkdir ${INSTALL_PREFIX}
  - travis_retry sudo apt-get update -qq

  - sudo apt-get install -y make cmake git build-essential wget doxygen libomp-dev libopenmpi-dev m4 unzip  libcurl4-openssl-dev

  # Python 3.7
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - travis_retry sudo apt-get update -qq
  - sudo apt-get install -y python3.7
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3.7 get-pip.py
  - sudo pip3.7 install numpy

    # Boost
  - cd $DEPS_DIR
  - travis_retry wget https://dl.bintray.com/boostorg/release/${BOOST_MAJOR_VERSION}.${BOOST_MINOR_VERSION}.${BOOST_RELEASE_VERSION}/source/boost_${BOOST_MAJOR_VERSION}_${BOOST_MINOR_VERSION}_${BOOST_RELEASE_VERSION}.tar.bz2
  - tar xvf boost_${BOOST_MAJOR_VERSION}_${BOOST_MINOR_VERSION}_${BOOST_RELEASE_VERSION}.tar.bz2 &>/dev/null
  - cd boost_${BOOST_MAJOR_VERSION}_${BOOST_MINOR_VERSION}_${BOOST_RELEASE_VERSION}
  - CXX=${COMPILER_CPP} ./bootstrap.sh --with-python=`which python3.7` --with-libraries=python --with-test --prefix=$INSTALL_PREFIX
  - travis_wait 30 ./b2 -d0 --link=static threading=multi --toolset=$CC --layout=tagged install

  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${INSTALL_PREFIX}/lib:${INSTALL_PREFIX}/lib64

script:

  - cd ${TRAVIS_BUILD_DIR}
  -
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$(which ${CXX}) -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${INSTALL_PREFIX}
  - make
  - ./fbmtest/fbmtest
  - PYTHONPATH=$PYTHONPATH:. python3.7 ../pythontests/test_fbm.py
